#import click
#
#
#@click.command()
#def main():
#    click.echo("This is gsf's command line interface.")



import click
import os
import twobody
import gc


@click.command()
@click.argument('file_star', type=click.Path(exists=True, readable=True), nargs=1)
@click.argument('file_gas', type=click.Path(exists=True, readable=True), nargs=1)
@click.argument('file_dark', type=click.Path(exists=True, readable=True), nargs=1)
def main(file_star, file_gas, file_dark, filters=None, out_dir=None, eps=0.1, radius_align=None, trig_scaling=None,
         varlist=['jzjc','jpjc','e'], number_of_clusters=2, covariance_type='full', whiten_data=True, n_init=1, 
         plot=True, band=False, M2L=False, inclination=90., fov=None, verbose=True):
    """
    This is the main function of GalacticStructureFinder (GSF)

    GSF separates the stellar particles in a simulated dark matter halo into a 
    fixed number of components using Gaussian Mixture Models in an arbitrary, 
    user-defined feature space. 
    
    The only required input are three files containing the star, gas, and dark 
    matter particles properties, in this order. The galaxy is assumed isolated, 
    and centered, and the expected units are: Msun for masses, kpc for Cartesian
    coordinates, and km/s for Cartesian velocities.  

    Parameters
    ----------
    filters : dict, default=None
        A dictionary with rules to select a subsample of the stellar particles for
        clustering using only LowPass, HighPass and BandPass on available or derivable
        features.

    out_dir : string, default=None
        Path to the directory where all data should be saved. If None, gsf will create 
        a new directory output/ in the running directory. 

    eps : float, default=0.1
        Minimum particle separation in kpc units to ensure non-divergent values for 
        the gravitational potential and acceleration at all particle positions. 

    radius_align : float, default=None
        The 3D radius in kpc of the farthest particle to consider for orienting the galaxy.
        If None, assumed to be 0.1*rvir. 

    trig_scaling : list of bool, default=None
        Setting any of the trig_scaling elements to True will result in the corresponding 
        input feature being scaled as arctan(feature/std(feature)). This might be a good idea 
        for features with large dynamical ranges.
        
    varlist : list of strings, default=['jzjc','jpjc','e']
        The list of desired features on which to run the clustering. It can contain any 
        combination of features either available in file_star or derivable from those 
        available, as listed in the function available_features(), and constructed in the 
        function generate_tmp_file(). Adding new features requires altering the following 
        functions: available_features (add the feature name as a new string), 
        generate_tmp_file (add the rule on how to compute the feature, if not directly 
        available in correct units in file_star), and optionally feature_labels (add the 
        nice latex formatting for the feature name). Any property available in the tmp_file
        generated by the function generate_tmp_file is a potentially valid feature.  

    number_of_clusters :  int, default=2
        Number of multi-dimensional Gaussians or galaxy components. 
        
    covariance_type : string, default='full'
        By default each clustering component is assumed to have its own general covariance 
        matrix ('full'). The other options are: 'tied', 'spherical' and 'diag'. For details, 
        check the sklearn documentation at https://scikit-learn.org/stable/modules/generated/
        
    whiten_data: bool, default=True
        Center the clustering feature space to the mean and scaled to unit variance, feature
        by feature. WARNING: do not set to False if the different features have (very) different 
        dynamical ranges! 
    
    n_init: int, default=1
        The Expectation-Maximization algorithm of sklearn runs for up to 100 times or until 
        the convergence threshold is met (1.0e-03), using n_init k-means initializations for
        the clusters. WARNING: you might need a larger value to get convergence!

    plot: bool, default=True
        Plot the 1st, 2nd and 3rd order moment maps for all components and the full galaxy in 
        one figure. If gsf is called in a loop to find the optimal number of components, setting 
        it to False is more efficient.  
        
    band: bool, default=False
        If the band is True, and there is a luminosity feature in the tmp_file, the moments maps
        figure will be done weighting with particle luminosity instead of particle mass. 
    
    M2L: float, default=None 
        If the mass-to-light M2L is given, the weighting for the moemnts maps figure will be done 
        with the luminosities computed from masses. In practice, the M2L option only changes the 
        units in the surface density panel from Msun/pc^2 to Lsun/pc^2. The band arg has precedence 
        over M2L.

    inclination: float, default=90.
        Angle in degrees setting the image perspective. Default is to view the galaxy edge-on. 
        Should be a float or int between 0 (face-on) and 90 (edge-on). 
    
    fov: float, default=None
        Field-of-view value in kpc. It defaults to 50 kpc internally. 
        
    verbose: bool, default=True
        Gives some useful information that can e.g. speed up the run. 


    Attributes
    ----------

    See Also
    --------

    Notes
    -----

    Examples
    --------
    >>> import numpy as np
    """    

    if out_dir is None:
        os.system('mkdir output')
        out_dir = 'output/'

    start = time.time()

    print('Generate the two potential files that the clustering algorithm needs.')    
    if verbose:
        print('This is most likely the most time costly part of the run. To speed up,')
        print('set the env variable OMP_NUM_THREADS to the number of logical cpus you')
        print('could use on your machine, and restart gsf.')
    file_midplane = midplane_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps,radius_align=radius_align)
    file_potential = star_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps)

    print('Generate large file tmp_file that will be used to select the clustering')
    print('feature space, and define what properties for the clusters can be computed.')
    tmp_file = generate_tmp_file(file_star,file_potential,file_midplane,out_dir=out_dir,filters=filters)

    print('Generate the input file for clustering.')
    GMM_input_file = GMM_input(tmp_file,varlist=varlist,trig_scaling=trig_scaling)
    data_input = pickle.load(open(GMM_input_file,'rb'))
    effective_varlist = data_input['feature_space']
    del(data_input)
    print('GSF will run the clustering in the input space: ',effective_varlist)

    #Get the available features from the *.tmp file
    features_in_tmp_file = get_list_of_tags_from_file(tmp_file)
    tags = []
    for feature in features_in_tmp_file:
        if feature not in ['iord','mass','luminosity','filters']: tags.append(feature) 
    
    print('Features that will appear in the diagnostic file: ',tags)

    n_param, logL, bic, aic, file_dec = gmm_clustering(GMM_input_file, number_of_clusters = number_of_clusters, covariance_type = covariance_type, 
                                                        whiten_data = whiten_data, n_init=n_init, plot=plot)
    
    print('Plot the results as the zero, first and second order moments maps.')
    plot_moment_maps(tmp_file, file_dec, inclination=inclination, band=band, M2L=M2L, fov=fov)
    
    finish = time.time()
    print('Total runtime: %s'%secondsToStr(finish-start))
    print('Finish')
    gc.collect()


if __name__ == "__main__":
    main()
