# Copyright (c) 2018--, Aura Obreja and the GalacticStructureFinder (gsf) contributors.
# GalacticStructureFinder decomposes simulated galaxies based on their stellar kinematics. 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# This program uses third-party libraries:
# - numpy (http://www.numpy.org/)
# - scipy (https://www.scipy.org/)
# - matplotlib (https://matplotlib.org/)
# - pynbody (https://github.com/pynbody/pynbody)
# - scikit-learn (http://scikit-learn.org/stable/)
# Please refer to the original licensing conditions for each of these third party software libraries. 
# 
# If you use this program or parts of it, please cite the original article presenting gsf: 
# Obreja, Maccio, Moster et al MNRAS 2018, "Introducing galactic structure finder: the 
# multiple stellar kinematic structures of a Milky Way mass galaxy" 2018MNRAS.477.4915O 
#  

import pickle, os, gc, time
import numpy as np
from .domath import secondsToStr
from .dopotential import star_potential, midplane_potential
from .doclustering import GMM_input, gmm_clustering
from .doplots import plot_moment_maps, plot_diagnostic
from .features import generate_tmp_file, get_list_of_tags_from_file
from .model_selection import select_optimal_model
from .dosummary import compute_percentiles


def gsf(file_star, file_gas, file_dark, varlist='jzjc,jpjc,e', number_of_clusters=2, out_dir=None,  
        eps=0.1, radius_align=None, trig_scaling=None, covariance_type='full', whiten_data=True, n_init=1, 
        plot=True, band=False, M2L=False, inclination=90., fov=None, verbose=True, filters=None):
    """
    This is the main function of GalacticStructureFinder (GSF)

    GSF separates the stellar particles in a simulated dark matter halo into a 
    fixed number of components using Gaussian Mixture Models in an arbitrary, 
    user-defined feature space. 
    
    The only required input are three files containing the star, gas, and dark 
    matter particles properties, in this order. The galaxy is assumed isolated, 
    and centered, and the expected units are: Msun for masses, kpc for Cartesian
    coordinates, and km/s for Cartesian velocities.  

    Parameters
    ----------
    varlist : string, default='jzjc,jpjc,e'
        Comma separated names of the desired features on which to run the clustering. 
        It can contain any combination of features either available in file_star or 
        derivable from those available, as listed in the function available_features(), 
        and constructed in the function generate_tmp_file(). Adding new features requires 
        altering the following functions: available_features (add the feature name as a new string), 
        generate_tmp_file (add the rule on how to compute the feature, if not directly 
        available in correct units in file_star), and optionally feature_labels (add the 
        nice latex formatting for the feature name). Any property available in the tmp_file
        generated by the function generate_tmp_file is a potentially valid feature.  

    number_of_clusters :  int, default=2
        Number of multi-dimensional Gaussians or galaxy components. 

    out_dir : string, default=None
        Path to the directory where all data should be saved. If None, gsf will create 
        a new directory output/ in the running directory. 

    filters : dict, default=None
        A dictionary with rules to select a subsample of the stellar particles for
        clustering using only LowPass, HighPass and BandPass on available or derivable
        features.

    eps : float, default=0.1
        Gravitatonal softening in kpc. Represents the minimum particle separation 
        that ensures non-divergent values for the gravitational potential and acceleration 
        at all particle positions. 

    radius_align : float, default=None
        The 3D radius of the farthest particle to consider for orienting the galaxy.
        Can be either in fraction of rvir or in kpc. If None, assumed to be 0.1*rvir. 
        
    trig_scaling : list of bool, default=None
        Setting any of the trig_scaling elements to True will result in the corresponding 
        input feature being scaled as arctan(feature/std(feature)). This might be a good idea 
        for features with large dynamical ranges.
        
    covariance_type : string, default='full'
        By default each clustering component is assumed to have its own general covariance 
        matrix ('full'). The other options are: 'tied', 'spherical' and 'diag'. For details, 
        check the sklearn documentation at https://scikit-learn.org/stable/modules/generated/
        
    whiten_data: bool, default=True
        Center the clustering feature space to the mean and scaled to unit variance, feature
        by feature. WARNING: do not set to False if the different features have (very) different 
        dynamical ranges! 
    
    n_init: int, default=1
        The Expectation-Maximization algorithm of sklearn runs for up to 100 times or until 
        the convergence threshold is met (1.0e-03), using n_init k-means initializations for
        the clusters. WARNING: you might need a larger value to get convergence!

    plot: bool, default=True
        Plot the 1st, 2nd and 3rd order moment maps for all components and the full galaxy in 
        one figure. If gsf is called in a loop to find the optimal number of components, setting 
        it to False is more efficient.  
        
    band: bool, default=False
        If the band is True, and there is a luminosity feature in the tmp_file, the moments maps
        figure will be done weighting with particle luminosity instead of particle mass. 
    
    M2L: float, default=None 
        If the mass-to-light M2L is given, the weighting for the moemnts maps figure will be done 
        with the luminosities computed from masses. In practice, the M2L option only changes the 
        units in the surface density panel from Msun/pc^2 to Lsun/pc^2. The band arg has precedence 
        over M2L.

    inclination: float, default=90.
        Angle in degrees setting the image perspective. Default is to view the galaxy edge-on. 
        Should be a float or int between 0 (face-on) and 90 (edge-on). 
    
    fov: float, default=None
        Field-of-view value in kpc. It defaults to 50 kpc internally. 
        
    verbose: bool, default=True
        Gives some useful information that can e.g. speed up the run. 

    Notes
    -----
        It creates two png figures and one data file.
    """    

    # Transform varlist from a string to a list of strings
    varlist = varlist.split(',')

    if out_dir is None:
        os.system('mkdir output')
        out_dir = 'output/'

    start = time.time()

    print('Generate the two potential files that the clustering algorithm needs.')    
    if verbose:
        print('This is most likely the most time costly part of the run. To speed up,')
        print('set the env variable OMP_NUM_THREADS to the number of logical cpus you')
        print('could use on your machine, and restart gsf.')
    file_midplane = midplane_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps,radius_align=radius_align)
    file_potential = star_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps)

    print('Generate the large file tmp_file that will be used to select the clustering')
    print('feature space, and define what properties for the clusters can be computed.')
    tmp_file = generate_tmp_file(file_star,file_potential,file_midplane,out_dir=out_dir,filters=filters)

    print('Generate the input file for clustering.')
    GMM_input_file = GMM_input(tmp_file,varlist=varlist,trig_scaling=trig_scaling)
    data_input = pickle.load(open(GMM_input_file,'rb'))
    effective_varlist = data_input['feature_space']
    del(data_input)
    print('GSF will run the clustering in the input space: ',effective_varlist)

    _, _, _, _, file_dec = gmm_clustering(GMM_input_file, number_of_clusters = number_of_clusters, 
                                          covariance_type = covariance_type, whiten_data = whiten_data, 
                                          n_init=n_init, plot=plot)
    
    print('Plot the results as the zero, first and second order moments maps.')
    plot_moment_maps(tmp_file, file_dec, inclination=inclination, band=band, M2L=M2L, fov=fov)
    
    finish = time.time()
    print('Total runtime: %s'%secondsToStr(finish-start))
    print('Finish')
    gc.collect()

    return


def gsf_loop(file_star, file_gas, file_dark, varlist='jzjc,jpjc,e', out_dir=None, 
             eps=0.1, radius_align=None, trig_scaling=None, covariance_type='full', whiten_data=True, 
             n_init=1, plot=False, verbose=True, filters=None):
    """
    This is the loop function of GalacticStructureFinder (GSF). It will run the gsf function 
    for all consecutive models between number_of_clusters=1 and number_of_clusters=15,
    and create a diagnostic file with a dictionary containing the summary statistics 
    (16th, 50th and 84th percentiles) of all stellar properties available or derivable, 
    for all components of all 15 models. The diagnostic file also contains integrated 
    properties of all these components, like e.g.: total mass, total luminosity (if 
    luminosity is available in file_star), eigenvalues and eigenvectors of the inertia 
    tensor, angular momentum vector.   

    GSF separates the stellar particles in a simulated dark matter halo into a 
    fixed number of components using Gaussian Mixture Models in an arbitrary, 
    user-defined feature space. 
    
    The only required input are three files containing the star, gas, and dark 
    matter particles properties, in this order. The galaxy is assumed isolated, 
    and centered, and the expected units are: Msun for masses, kpc for Cartesian
    coordinates, and km/s for Cartesian velocities.  

    Parameters
    ----------
    varlist : string, default='jzjc,jpjc,e'
        Comma separated names of the desired features on which to run the clustering. 
        It can contain any combination of features either available in file_star or 
        derivable from those available, as listed in the function available_features(), 
        and constructed in the function generate_tmp_file(). Adding new features requires 
        altering the following functions: available_features (add the feature name as a new string), 
        generate_tmp_file (add the rule on how to compute the feature, if not directly 
        available in correct units in file_star), and optionally feature_labels (add the 
        nice latex formatting for the feature name). Any property available in the tmp_file
        generated by the function generate_tmp_file is a potentially valid feature.  
        
    out_dir : string, default=None
        Path to the directory where all data should be saved. If None, gsf will create 
        a new directory output/ in the running directory. 

    filters : dict, default=None
        A dictionary with rules to select a subsample of the stellar particles for
        clustering using only LowPass, HighPass and BandPass on available or derivable
        features.

    eps : float, default=0.1
        Gravitatonal softening in kpc. Represents the minimum particle separation 
        that ensures non-divergent values for the gravitational potential and acceleration 
        at all particle positions. 

    radius_align : float, default=None
        The 3D radius of the farthest particle to consider for orienting the galaxy.
        Can be either in fraction of rvir or in kpc. If None, assumed to be 0.1*rvir. 
        
    trig_scaling : list of bool, default=None
        Setting any of the trig_scaling elements to True will result in the corresponding 
        input feature being scaled as arctan(feature/std(feature)). This might be a good idea 
        for features with large dynamical ranges.
        
    covariance_type : string, default='full'
        By default each clustering component is assumed to have its own general covariance 
        matrix ('full'). The other options are: 'tied', 'spherical' and 'diag'. For details, 
        check the sklearn documentation at https://scikit-learn.org/stable/modules/generated/
        
    whiten_data: bool, default=True
        Center the clustering feature space to the mean and scaled to unit variance, feature
        by feature. WARNING: do not set to False if the different features have (very) different 
        dynamical ranges! 
    
    n_init: int, default=1
        The Expectation-Maximization algorithm of sklearn runs for up to 100 times or until 
        the convergence threshold is met (1.0e-03), using n_init k-means initializations for
        the clusters. WARNING: you might need a larger value to get convergence!

    plot: bool, default=True
        Plot the 1st, 2nd and 3rd order moment maps for all components and the full galaxy in 
        one figure. If gsf is called in a loop to find the optimal number of components, setting 
        it to False is more efficient.  
        
    band: bool, default=False
        If the band is True, and there is a luminosity feature in the tmp_file, the moments maps
        figure will be done weighting with particle luminosity instead of particle mass. 
    
    M2L: float, default=None 
        If the mass-to-light M2L is given, the weighting for the moemnts maps figure will be done 
        with the luminosities computed from masses. In practice, the M2L option only changes the 
        units in the surface density panel from Msun/pc^2 to Lsun/pc^2. The band arg has precedence 
        over M2L.

    inclination: float, default=90.
        Angle in degrees setting the image perspective. Default is to view the galaxy edge-on. 
        Should be a float or int between 0 (face-on) and 90 (edge-on). 
    
    fov: float, default=None
        Field-of-view value in kpc. It defaults to 50 kpc internally. 
        
    verbose: bool, default=True
        Gives some useful information that can e.g. speed up the run. 

    Notes
    -----
        For each model from number_of_clusters=1 to number_of_clusters=15, this function creates one 
        data file with the probabilities of stellar particles of belonging to each cluster, and a png 
        figure with the distributions of these clusters in all the 2D projections of the clustering 
        input space. Finally, it generates a files containing the dictionary of summary statistics for 
        all these models and the dictionary ranking the models from best to worst, and a png figure 
        with the optimal models according to the elbow method in the log likelihood vs number of free 
        parameters space.  
    """    

    # Transform varlist from a string to a list of strings
    varlist = varlist.split(',')

    if out_dir is None:
        os.system('mkdir output')
        out_dir = 'output/'

    start = time.time()
    
    print('Generate the files that the clustering algorithm needs...')
    file_potential = star_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps,verbose=verbose)
    file_midplane = midplane_potential(file_star,file_dark,file_gas,out_dir=out_dir,eps=eps,radius_align=radius_align,verbose=verbose)
    tmp_file = generate_tmp_file(file_star,file_potential,file_midplane,out_dir=out_dir,filters=filters,verbose=verbose)
    GMM_input_file = GMM_input(tmp_file,varlist=varlist,trig_scaling=trig_scaling,verbose=verbose)
    data_input = pickle.load(open(GMM_input_file,'rb'))
    effective_varlist = data_input['feature_space']

    #get the available features from the *.tmp file
    features_in_tmp_file = get_list_of_tags_from_file(tmp_file)
    tags = []
    for feature in features_in_tmp_file:
        if feature not in ['iord','mass','luminosity','filters']: tags.append(feature) 
    
    print('Features that will appear in the diagnostic file: ',tags)
    
    print('Run the clustering from nk=1 to nk=15')
    # initialize two nested dictionaries to contain the 16th, 50th and 84th percentiles of all features for all clusters of all mixture models
    data_massw = {} # nested dictionary where the percentiles will be computed using mass weighting  
    data_lumw = {} # nested dictionary where the percentiles will be computed using luminosity weighting (if the luminosity is available in the tmp_file)
    for nk in np.arange(15)+1:
        data_massw[nk] = {}
        data_lumw[nk] = {}
        for feature in tags:
            data_massw[nk][feature] = {}
            data_lumw[nk][feature] = {}
            for percent in ['16','50','84']: 
                data_massw[nk][feature][percent] = np.nan
                data_lumw[nk][feature][percent] = np.nan

    BIC = []
    AIC = []
    nk = []
    num_param = []
    log_likelihood = []        
    for number_of_clusters in np.arange(15)+1:
        n_param, logL, bic, aic, file_dec = gmm_clustering(GMM_input_file, number_of_clusters = number_of_clusters, 
                                                           covariance_type = covariance_type, whiten_data = whiten_data, 
                                                           n_init=n_init, plot=plot)
        BIC.append(bic)
        AIC.append(aic)
        log_likelihood.append(logL)
        nk.append(number_of_clusters)
        num_param.append(n_param)
        compute_percentiles(tmp_file,file_dec,data_massw,data_lumw)
        gc.collect()

    diagnostic_png = GMM_input_file[:-4]+'.scikit_gmm_'+covariance_type+'_logLvsnk.png'
    if whiten_data: diagnostic_png = diagnostic_png[:-13]+'_white_logLvsnk.png'
    plot_diagnostic(nk,BIC,log_likelihood,diagnostic_png)
    nk_selected, nparam_selected, scree_selected = select_optimal_model(nk,num_param,log_likelihood,figout=diagnostic_png[:-12]+'STvsNparam.png')
    
    diagnostic_file = diagnostic_png[:-12]+'diagnostics.dat'
    f = open(diagnostic_file,'wb')
    pickle.dump({'mixture_features':effective_varlist,'nk':np.array(nk),'num_param':np.array(num_param),
                 'log_likelihood':np.array(log_likelihood),'BIC':np.array(BIC),'AIC':np.array(AIC),
                 'mwp':data_massw,'lwp':data_lumw,
                 'CHull_model_selection':{'nk':nk_selected,'num_param':nparam_selected,'scree':scree_selected}},f)
    f.close()
    del(f)
    gc.collect()
    
    finish = time.time()
    print('Total runtime: %s'%secondsToStr(finish-start))
    print('Finish')
    
    gc.collect()
    return 